apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: hello-world
spec:
  gateways:
  - istio-ingress/gateway
  hosts:
  - hello-world.hello-world.svc.cluster.local
  - mydomain.com
  http:
  - timeout: 5s
    route:
    - destination:
        host: hello-world.hello-world.svc.cluster.local

